# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChiesCakesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
