# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChiesCakesApp', '0003_auto_20180815_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
    ]
