# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChiesCakesApp', '0004_remove_reviews_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='picture',
            new_name='img_url',
        ),
    ]
